# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\python_worksapce\Rally_Breizh_Furious\accueil3.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Fenetre(object):
    def setupUi(self, Fenetre):
        Fenetre.setObjectName(_fromUtf8("Fenetre"))
        Fenetre.resize(1050, 890)
        Fenetre.setMaximumSize(QtCore.QSize(16777215, 9154))
        Fenetre.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/background/realracing3.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Fenetre.setWindowIcon(icon)
        Fenetre.setAutoFillBackground(False)
        Fenetre.setStyleSheet(_fromUtf8("QWidget {background-color: rgb(104, 104, 104);\n"
"\n"
"}\n"
"QPushButton {\n"
"   /* background-color: beige;*/\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: red;\n"
"    font: bold  30px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"    background-color:  rgb(104, 104, 104);\n"
"color: beige;\n"
"    border-style: inset;\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"    background-color:  rgb(104, 104, 104);\n"
"color: beige;\n"
"    border-style: inset;\n"
"\n"
"}"))
        self.verticalLayout = QtGui.QVBoxLayout(Fenetre)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.stackedWidget = QtGui.QStackedWidget(Fenetre)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.waccueil = QtGui.QWidget()
        self.waccueil.setStyleSheet(_fromUtf8("/*background-image: url(\'Z:/python_worksapce/Rally_Breizh_Furious/images/background/realracing3.jpg\');\n"
"*/"))
        self.waccueil.setObjectName(_fromUtf8("waccueil"))
        self.label_titre = QtGui.QLabel(self.waccueil)
        self.label_titre.setGeometry(QtCore.QRect(-190, -30, 1292, 181))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Franklin Gothic Medium Cond"))
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_titre.setFont(font)
        self.label_titre.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);"))
        self.label_titre.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titre.setObjectName(_fromUtf8("label_titre"))
        self.label = QtGui.QLabel(self.waccueil)
        self.label.setGeometry(QtCore.QRect(0, 130, 1231, 781))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("images/background/realracing3.jpg")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.btnOptions = QtGui.QPushButton(self.waccueil)
        self.btnOptions.setGeometry(QtCore.QRect(50, 410, 579, 51))
        self.btnOptions.setObjectName(_fromUtf8("btnOptions"))
        self.btnQuitter = QtGui.QPushButton(self.waccueil)
        self.btnQuitter.setGeometry(QtCore.QRect(50, 470, 579, 51))
        font = QtGui.QFont()
 #       font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnQuitter.setFont(font)
        self.btnQuitter.setObjectName(_fromUtf8("btnQuitter"))
        self.btnJouer = QtGui.QPushButton(self.waccueil)
        self.btnJouer.setGeometry(QtCore.QRect(60, 340, 571, 51))
        self.btnJouer.setObjectName(_fromUtf8("btnJouer"))
        self.label.raise_()
        self.btnOptions.raise_()
        self.btnQuitter.raise_()
        self.label_titre.raise_()
        self.btnJouer.raise_()
        self.stackedWidget.addWidget(self.waccueil)
        self.joueurs = QtGui.QWidget()
        self.joueurs.setObjectName(_fromUtf8("joueurs"))
        self.btnJoueurs = QtGui.QPushButton(self.joueurs)
        self.btnJoueurs.setGeometry(QtCore.QRect(60, 340, 571, 51))
        self.btnJoueurs.setObjectName(_fromUtf8("btnJoueurs"))
        self.btonChoixOrdianateurs = QtGui.QPushButton(self.joueurs)
        self.btonChoixOrdianateurs.setGeometry(QtCore.QRect(50, 490, 571, 51))
        self.btonChoixOrdianateurs.setObjectName(_fromUtf8("btonChoixOrdianateurs"))
        self.label_2 = QtGui.QLabel(self.joueurs)
        self.label_2.setGeometry(QtCore.QRect(-250, 20, 1181, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Franklin Gothic Medium"))
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.labelbackground2 = QtGui.QLabel(self.joueurs)
        self.labelbackground2.setGeometry(QtCore.QRect(-30, 140, 1401, 781))
        self.labelbackground2.setText(_fromUtf8(""))
        self.labelbackground2.setPixmap(QtGui.QPixmap(_fromUtf8("images/background/realracing3.jpg")))
        self.labelbackground2.setScaledContents(True)
        self.labelbackground2.setObjectName(_fromUtf8("labelbackground2"))
        self.pushButton_2 = QtGui.QPushButton(self.joueurs)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 420, 571, 51))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.labelbackground2.raise_()
        self.btnJoueurs.raise_()
        self.btonChoixOrdianateurs.raise_()
        self.label_2.raise_()
        self.pushButton_2.raise_()
        self.stackedWidget.addWidget(self.joueurs)
        self.voitures = QtGui.QWidget()
        self.voitures.setObjectName(_fromUtf8("voitures"))
        self.label_3 = QtGui.QLabel(self.voitures)
        self.label_3.setGeometry(QtCore.QRect(70, 70, 1244, 38))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Franklin Gothic Medium Cond"))
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.btnSuivant = QtGui.QPushButton(self.voitures)
        self.btnSuivant.setGeometry(QtCore.QRect(550, 820, 461, 51))
        font = QtGui.QFont()
#        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnSuivant.setFont(font)
        self.btnSuivant.setObjectName(_fromUtf8("btnSuivant"))
        self.btnPrecedent = QtGui.QPushButton(self.voitures)
        self.btnPrecedent.setGeometry(QtCore.QRect(20, 820, 496, 51))
        font = QtGui.QFont()
       # font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnPrecedent.setFont(font)
        self.btnPrecedent.setObjectName(_fromUtf8("btnPrecedent"))
        self.label_4 = QtGui.QLabel(self.voitures)
        self.label_4.setGeometry(QtCore.QRect(680, 200, 761, 38))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Franklin Gothic Medium Cond"))
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.voitures)
        self.label_5.setGeometry(QtCore.QRect(690, 310, 761, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Franklin Gothic Medium Cond"))
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.voitures)
        self.label_6.setGeometry(QtCore.QRect(870, 200, 761, 38))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Franklin Gothic Medium Cond"))
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.voitures)
        self.label_7.setGeometry(QtCore.QRect(870, 310, 761, 38))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Franklin Gothic Medium Cond"))
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.voitures)
        self.label_8.setGeometry(QtCore.QRect(140, 300, 201, 331))
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setPixmap(QtGui.QPixmap(_fromUtf8("images/car/v7.png")))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.stackedWidget.addWidget(self.voitures)
        self.circuits = QtGui.QWidget()
        self.circuits.setObjectName(_fromUtf8("circuits"))
        self.label_9 = QtGui.QLabel(self.circuits)
        self.label_9.setGeometry(QtCore.QRect(40, 80, 1244, 38))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Franklin Gothic Medium Cond"))
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.btnSuivantCircuit = QtGui.QPushButton(self.circuits)
        self.btnSuivantCircuit.setGeometry(QtCore.QRect(550, 810, 496, 51))
        font = QtGui.QFont()
       # font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnSuivantCircuit.setFont(font)
        self.btnSuivantCircuit.setObjectName(_fromUtf8("btnSuivantCircuit"))
        self.btnPrecedentCircuit = QtGui.QPushButton(self.circuits)
        self.btnPrecedentCircuit.setGeometry(QtCore.QRect(20, 810, 496, 51))
        font = QtGui.QFont()
        #font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnPrecedentCircuit.setFont(font)
        self.btnPrecedentCircuit.setObjectName(_fromUtf8("btnPrecedentCircuit"))
        self.label_10 = QtGui.QLabel(self.circuits)
        self.label_10.setGeometry(QtCore.QRect(170, 230, 601, 291))
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setPixmap(QtGui.QPixmap(_fromUtf8("images/motifs/road_bent.png")))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.stackedWidget.addWidget(self.circuits)
        self.stackedWidgetPage4 = QtGui.QWidget()
        self.stackedWidgetPage4.setObjectName(_fromUtf8("stackedWidgetPage4"))
        self.label_11 = QtGui.QLabel(self.stackedWidgetPage4)
        self.label_11.setGeometry(QtCore.QRect(40, 70, 1244, 38))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Franklin Gothic Medium Cond"))
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.stackedWidget.addWidget(self.stackedWidgetPage4)
        self.wjeu = QtGui.QWidget()
        self.wjeu.setObjectName(_fromUtf8("wjeu"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.wjeu)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.stackedWidget.addWidget(self.wjeu)
        self.wclassement = QtGui.QWidget()
        font = QtGui.QFont()
        font.setPointSize(12)
        self.wclassement.setFont(font)
        self.wclassement.setObjectName(_fromUtf8("wclassement"))
        self.label_13 = QtGui.QLabel(self.wclassement)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 1280, 60))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Franklin Gothic Medium Cond"))
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.listClassement = QtGui.QListView(self.wclassement)
        self.listClassement.setGeometry(QtCore.QRect(20, 80, 971, 721))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.listClassement.setFont(font)
        self.listClassement.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.listClassement.setObjectName(_fromUtf8("listClassement"))
        self.btnMenu = QtGui.QPushButton(self.wclassement)
        self.btnMenu.setGeometry(QtCore.QRect(420, 830, 570, 51))
        self.btnMenu.setObjectName(_fromUtf8("btnMenu"))
        self.stackedWidget.addWidget(self.wclassement)
        self.stackedWidgetPage7 = QtGui.QWidget()
        self.stackedWidgetPage7.setObjectName(_fromUtf8("stackedWidgetPage7"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.stackedWidgetPage7)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.stackedWidget.addWidget(self.stackedWidgetPage7)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(Fenetre)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.btnQuitter, QtCore.SIGNAL(_fromUtf8("clicked()")), Fenetre.close)
        QtCore.QMetaObject.connectSlotsByName(Fenetre)

    def retranslateUi(self, Fenetre):
        Fenetre.setWindowTitle(_translate("Fenetre", "Form", None))
        self.label_titre.setText(_translate("Fenetre", "_____________________** RALLY FAST FURIUS**__________________", None))
        self.btnOptions.setText(_translate("Fenetre", "OPTIONS", None))
        self.btnQuitter.setText(_translate("Fenetre", "QUITTER", None))
        self.btnJouer.setText(_translate("Fenetre", "JOUER", None))
        self.btnJoueurs.setText(_translate("Fenetre", "1 JOUEUR", None))
        self.btonChoixOrdianateurs.setText(_translate("Fenetre", "ORDINATEURS", None))
        self.label_2.setText(_translate("Fenetre", "_____________________** RALLY FAST FURIUS**__________________", None))
        self.pushButton_2.setText(_translate("Fenetre", "2 Joueurs", None))
        self.label_3.setText(_translate("Fenetre", "CHOISISSEZ VOTRE CAR ", None))
        self.btnSuivant.setText(_translate("Fenetre", "SUIVANT >", None))
        self.btnPrecedent.setText(_translate("Fenetre", "< PRECEDENT", None))
        self.label_4.setText(_translate("Fenetre", "VITESSE MAX:", None))
        self.label_5.setText(_translate("Fenetre", "RESERVOIR:", None))
        self.label_6.setText(_translate("Fenetre", "200km/h", None))
        self.label_7.setText(_translate("Fenetre", "100L", None))
        self.label_9.setText(_translate("Fenetre", "CHOISISSEZ VOTRE CIRCUIT", None))
        self.btnSuivantCircuit.setText(_translate("Fenetre", "SUIVANT >", None))
        self.btnPrecedentCircuit.setText(_translate("Fenetre", "< PRECEDENT", None))
        self.label_11.setText(_translate("Fenetre", "MEILLEUR SCORE", None))
        self.label_13.setText(_translate("Fenetre", "Classement ", None))
        self.btnMenu.setText(_translate("Fenetre", "Menu", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Fenetre = QtGui.QWidget()
    ui = Ui_Fenetre()
    ui.setupUi(Fenetre)
    Fenetre.show()
    sys.exit(app.exec_())

